// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth/auth.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Request struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Service              string   `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Method               string   `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Request) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Request) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type Response struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	User                 *User    `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Response) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "auth.User")
	proto.RegisterType((*Request)(nil), "auth.Request")
	proto.RegisterType((*Response)(nil), "auth.Response")
}

func init() { proto.RegisterFile("proto/auth/auth.proto", fileDescriptor_82b5829f48cfb8e5) }

var fileDescriptor_82b5829f48cfb8e5 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0x80, 0x49, 0x9a, 0xa6, 0xe1, 0x50, 0x19, 0x2c, 0x40, 0x56, 0x07, 0x84, 0x32, 0xa0, 0x4e,
	0xad, 0x54, 0x9e, 0x80, 0x9d, 0x29, 0x82, 0xee, 0x2e, 0x39, 0x11, 0x8b, 0x24, 0x4e, 0xfd, 0x53,
	0x16, 0x5e, 0x80, 0xb7, 0x46, 0x3e, 0x3b, 0xa0, 0x4a, 0x95, 0xba, 0xd8, 0xfe, 0xce, 0x77, 0xe7,
	0xef, 0x64, 0xb8, 0x1d, 0xb4, 0xb2, 0x6a, 0x2d, 0x9c, 0x6d, 0x68, 0x59, 0x11, 0xb3, 0xcc, 0x9f,
	0xcb, 0x6f, 0xc8, 0xde, 0x0c, 0x6a, 0x76, 0x0d, 0xa9, 0xac, 0x79, 0xf2, 0x90, 0x2c, 0x2f, 0xab,
	0x54, 0xd6, 0x6c, 0x01, 0x85, 0x33, 0xa8, 0x7b, 0xd1, 0x21, 0x4f, 0x29, 0xfa, 0xc7, 0xec, 0x0e,
	0xf2, 0x4e, 0xed, 0x64, 0x8b, 0x7c, 0x42, 0x37, 0x91, 0xd8, 0x0d, 0x4c, 0xb1, 0x13, 0xb2, 0xe5,
	0x19, 0x85, 0x03, 0xf8, 0x4e, 0x83, 0x30, 0xe6, 0x4b, 0xe9, 0x9a, 0x4f, 0x43, 0xa7, 0x91, 0xcb,
	0x3d, 0xcc, 0x2a, 0xdc, 0x3b, 0x34, 0xd6, 0x17, 0x5b, 0xf5, 0x89, 0x7d, 0x74, 0x08, 0xc0, 0xee,
	0x21, 0xf3, 0xcf, 0x92, 0xc2, 0xd5, 0x06, 0x56, 0xe4, 0xef, 0x85, 0x2b, 0x8a, 0x33, 0x0e, 0x33,
	0x83, 0xfa, 0x20, 0xdf, 0x47, 0x97, 0x11, 0x49, 0x12, 0x6d, 0xa3, 0xea, 0x68, 0x13, 0xa9, 0xdc,
	0x42, 0x51, 0xa1, 0x19, 0x54, 0x6f, 0x48, 0xf8, 0x20, 0xda, 0x38, 0x77, 0x51, 0x05, 0xf8, 0x37,
	0x49, 0x4f, 0x99, 0x4c, 0x4e, 0x9b, 0x6c, 0x7e, 0x12, 0xc8, 0x9e, 0x9d, 0x6d, 0xd8, 0x63, 0xdc,
	0xe7, 0x21, 0x25, 0xce, 0xb7, 0x38, 0xc6, 0xf2, 0x82, 0x2d, 0x21, 0x7f, 0x51, 0x1f, 0xca, 0xd9,
	0xb3, 0x99, 0x6b, 0x98, 0x6f, 0xbd, 0x99, 0xb0, 0xf8, 0x4a, 0x2e, 0x67, 0x0a, 0x76, 0x39, 0xfd,
	0xf0, 0xd3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x38, 0xc5, 0xf4, 0xa0, 0xfa, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Auth service

type AuthClient interface {
	// 用户验证授权
	Auth(ctx context.Context, in *Request, opts ...client.CallOption) (*Request, error)
	// 用户退出登录
	Logout(ctx context.Context, in *Request, opts ...client.CallOption) (*Request, error)
	// token 验证
	ValidateToken(ctx context.Context, in *Request, opts ...client.CallOption) (*Request, error)
}

type authClient struct {
	c           client.Client
	serviceName string
}

func NewAuthClient(serviceName string, c client.Client) AuthClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "auth"
	}
	return &authClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *authClient) Auth(ctx context.Context, in *Request, opts ...client.CallOption) (*Request, error) {
	req := c.c.NewRequest(c.serviceName, "Auth.Auth", in)
	out := new(Request)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Logout(ctx context.Context, in *Request, opts ...client.CallOption) (*Request, error) {
	req := c.c.NewRequest(c.serviceName, "Auth.Logout", in)
	out := new(Request)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) ValidateToken(ctx context.Context, in *Request, opts ...client.CallOption) (*Request, error) {
	req := c.c.NewRequest(c.serviceName, "Auth.ValidateToken", in)
	out := new(Request)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthHandler interface {
	// 用户验证授权
	Auth(context.Context, *Request, *Request) error
	// 用户退出登录
	Logout(context.Context, *Request, *Request) error
	// token 验证
	ValidateToken(context.Context, *Request, *Request) error
}

func RegisterAuthHandler(s server.Server, hdlr AuthHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Auth{hdlr}, opts...))
}

type Auth struct {
	AuthHandler
}

func (h *Auth) Auth(ctx context.Context, in *Request, out *Request) error {
	return h.AuthHandler.Auth(ctx, in, out)
}

func (h *Auth) Logout(ctx context.Context, in *Request, out *Request) error {
	return h.AuthHandler.Logout(ctx, in, out)
}

func (h *Auth) ValidateToken(ctx context.Context, in *Request, out *Request) error {
	return h.AuthHandler.ValidateToken(ctx, in, out)
}
