// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/role/role.proto

package role

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Role struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName          string   `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_26e011caf756e89c, []int{0}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Role) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Role) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Role) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type ListQuery struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 int64    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Sort                 string   `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName          string   `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListQuery) Reset()         { *m = ListQuery{} }
func (m *ListQuery) String() string { return proto.CompactTextString(m) }
func (*ListQuery) ProtoMessage()    {}
func (*ListQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_26e011caf756e89c, []int{1}
}

func (m *ListQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListQuery.Unmarshal(m, b)
}
func (m *ListQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListQuery.Marshal(b, m, deterministic)
}
func (m *ListQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListQuery.Merge(m, src)
}
func (m *ListQuery) XXX_Size() int {
	return xxx_messageInfo_ListQuery.Size(m)
}
func (m *ListQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ListQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ListQuery proto.InternalMessageInfo

func (m *ListQuery) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListQuery) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListQuery) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *ListQuery) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListQuery) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

type Response struct {
	Role                 *Role    `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Roles                []*Role  `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	Total                int64    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Valid                bool     `protobuf:"varint,4,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_26e011caf756e89c, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *Response) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Response) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Response) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*Role)(nil), "role.Role")
	proto.RegisterType((*ListQuery)(nil), "role.ListQuery")
	proto.RegisterType((*Response)(nil), "role.Response")
}

func init() { proto.RegisterFile("proto/role/role.proto", fileDescriptor_26e011caf756e89c) }

var fileDescriptor_26e011caf756e89c = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0xb5, 0x6d, 0x3a, 0xd6, 0x5b, 0x99, 0x10, 0x14, 0x8a, 0xa0, 0xd4, 0x3e, 0xcd, 0x97, 0x09,
	0xf5, 0x0b, 0xf6, 0x2e, 0x82, 0xf9, 0x81, 0x11, 0x97, 0x20, 0x81, 0xac, 0x09, 0x49, 0x26, 0xee,
	0xcd, 0x1f, 0xf2, 0x1f, 0x25, 0x37, 0x71, 0x82, 0xc2, 0x5e, 0xda, 0x7b, 0xcf, 0x39, 0x6d, 0xce,
	0x39, 0x81, 0x2b, 0xeb, 0x4c, 0x30, 0x0f, 0xce, 0x68, 0x89, 0x8f, 0x15, 0xee, 0x94, 0xc4, 0x79,
	0xf8, 0x2a, 0x80, 0x30, 0xa3, 0x25, 0x5d, 0x40, 0xa9, 0x44, 0x57, 0xf4, 0xc5, 0xb2, 0x62, 0xa5,
	0x12, 0x94, 0x02, 0x99, 0xf8, 0x4e, 0x76, 0x65, 0x5f, 0x2c, 0x1b, 0x86, 0x33, 0xbd, 0x83, 0x73,
	0xa1, 0xbc, 0xd5, 0xfc, 0xb0, 0x41, 0xae, 0x42, 0xae, 0xcd, 0xd8, 0x73, 0x94, 0xf4, 0xd0, 0x0a,
	0xe9, 0xb7, 0x4e, 0xd9, 0xa0, 0xcc, 0xd4, 0x91, 0xac, 0xf8, 0x85, 0xe8, 0x0d, 0xc0, 0xd6, 0x49,
	0x1e, 0xa4, 0xd8, 0xf0, 0xd0, 0xd5, 0x28, 0x68, 0x32, 0xb2, 0x0e, 0x91, 0xde, 0x5b, 0xf1, 0x43,
	0xcf, 0x12, 0x9d, 0x91, 0x75, 0x18, 0x3e, 0x0b, 0x68, 0x9e, 0x94, 0x0f, 0x2f, 0x7b, 0xe9, 0x0e,
	0xf4, 0x12, 0x6a, 0xad, 0x76, 0x2a, 0x64, 0xdf, 0x69, 0x89, 0xd6, 0x2d, 0x7f, 0x4b, 0xd6, 0x2b,
	0x86, 0x73, 0xc4, 0xbc, 0x71, 0x21, 0x5b, 0xc6, 0xf9, 0x18, 0x91, 0x9c, 0x88, 0x58, 0xff, 0x8b,
	0x38, 0x7c, 0xc0, 0x9c, 0x49, 0x6f, 0xcd, 0xe4, 0x25, 0xbd, 0x05, 0xac, 0x11, 0xcf, 0x6f, 0x47,
	0x58, 0x61, 0xbf, 0xb1, 0x4f, 0x86, 0x38, 0xed, 0xa1, 0x8e, 0x6f, 0xdf, 0x95, 0x7d, 0xf5, 0x47,
	0x90, 0x88, 0x18, 0x21, 0x98, 0xc0, 0x35, 0x3a, 0xab, 0x58, 0x5a, 0x22, 0xfa, 0xce, 0xb5, 0x12,
	0xe8, 0x6d, 0xce, 0xd2, 0x32, 0x8e, 0x50, 0x33, 0xfc, 0xe8, 0x1e, 0x48, 0x2c, 0x81, 0x5e, 0xa4,
	0xff, 0x1d, 0x0b, 0xb9, 0x5e, 0xe4, 0x03, 0xb2, 0xbf, 0xe1, 0xec, 0x75, 0x86, 0xb7, 0xfd, 0xf8,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0x72, 0xb6, 0x32, 0x59, 0x06, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Roles service

type RolesClient interface {
	// 权限验证授权
	// 获取权限列表
	List(ctx context.Context, in *ListQuery, opts ...client.CallOption) (*Response, error)
}

type rolesClient struct {
	c           client.Client
	serviceName string
}

func NewRolesClient(serviceName string, c client.Client) RolesClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "role"
	}
	return &rolesClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *rolesClient) List(ctx context.Context, in *ListQuery, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Roles.List", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Roles service

type RolesHandler interface {
	// 权限验证授权
	// 获取权限列表
	List(context.Context, *ListQuery, *Response) error
}

func RegisterRolesHandler(s server.Server, hdlr RolesHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Roles{hdlr}, opts...))
}

type Roles struct {
	RolesHandler
}

func (h *Roles) List(ctx context.Context, in *ListQuery, out *Response) error {
	return h.RolesHandler.List(ctx, in, out)
}
