stages:
- name: Build
  steps:
  - runScriptConfig:
      image: tetafro/golang-gcc:1.11-alpine
      shellScript: |-
        mkdir -p /go/src/github.com/gomsa
        ln -s `pwd` /go/src/github.com/gomsa/user-api
        cd /go/src/github.com/gomsa/user-api
        GO111MODULE=off
        CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o bin/service
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: user-api:${CICD_EXECUTION_SEQUENCE}
- name: Redis
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-redis
      version: 3.0.2
      answers:
        master.persistence.enabled: "true"
        cluster.slaveCount: "2"
      name: redis
      targetNamespace: api
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml