// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/frontPermit/frontPermit.proto

package frontPermit

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for FrontPermits service

type FrontPermitsService interface {
	// 权限验证授权
	// 全部权限
	All(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 获取权限列表
	List(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 根据 唯一 获取权限
	Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 创建权限
	Create(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 更新权限
	Update(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 删除权限
	Delete(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 同步前端权限 允许外部权限  需要最高 root 权限  *********高危 调用慎重*********
	UpdateOrCreate(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type frontPermitsService struct {
	c    client.Client
	name string
}

func NewFrontPermitsService(name string, c client.Client) FrontPermitsService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "frontPermit"
	}
	return &frontPermitsService{
		c:    c,
		name: name,
	}
}

func (c *frontPermitsService) All(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "FrontPermits.All", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontPermitsService) List(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "FrontPermits.List", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontPermitsService) Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "FrontPermits.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontPermitsService) Create(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "FrontPermits.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontPermitsService) Update(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "FrontPermits.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontPermitsService) Delete(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "FrontPermits.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontPermitsService) UpdateOrCreate(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "FrontPermits.UpdateOrCreate", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FrontPermits service

type FrontPermitsHandler interface {
	// 权限验证授权
	// 全部权限
	All(context.Context, *Request, *Response) error
	// 获取权限列表
	List(context.Context, *Request, *Response) error
	// 根据 唯一 获取权限
	Get(context.Context, *Request, *Response) error
	// 创建权限
	Create(context.Context, *Request, *Response) error
	// 更新权限
	Update(context.Context, *Request, *Response) error
	// 删除权限
	Delete(context.Context, *Request, *Response) error
	// 同步前端权限 允许外部权限  需要最高 root 权限  *********高危 调用慎重*********
	UpdateOrCreate(context.Context, *Request, *Response) error
}

func RegisterFrontPermitsHandler(s server.Server, hdlr FrontPermitsHandler, opts ...server.HandlerOption) error {
	type frontPermits interface {
		All(ctx context.Context, in *Request, out *Response) error
		List(ctx context.Context, in *Request, out *Response) error
		Get(ctx context.Context, in *Request, out *Response) error
		Create(ctx context.Context, in *Request, out *Response) error
		Update(ctx context.Context, in *Request, out *Response) error
		Delete(ctx context.Context, in *Request, out *Response) error
		UpdateOrCreate(ctx context.Context, in *Request, out *Response) error
	}
	type FrontPermits struct {
		frontPermits
	}
	h := &frontPermitsHandler{hdlr}
	return s.Handle(s.NewHandler(&FrontPermits{h}, opts...))
}

type frontPermitsHandler struct {
	FrontPermitsHandler
}

func (h *frontPermitsHandler) All(ctx context.Context, in *Request, out *Response) error {
	return h.FrontPermitsHandler.All(ctx, in, out)
}

func (h *frontPermitsHandler) List(ctx context.Context, in *Request, out *Response) error {
	return h.FrontPermitsHandler.List(ctx, in, out)
}

func (h *frontPermitsHandler) Get(ctx context.Context, in *Request, out *Response) error {
	return h.FrontPermitsHandler.Get(ctx, in, out)
}

func (h *frontPermitsHandler) Create(ctx context.Context, in *Request, out *Response) error {
	return h.FrontPermitsHandler.Create(ctx, in, out)
}

func (h *frontPermitsHandler) Update(ctx context.Context, in *Request, out *Response) error {
	return h.FrontPermitsHandler.Update(ctx, in, out)
}

func (h *frontPermitsHandler) Delete(ctx context.Context, in *Request, out *Response) error {
	return h.FrontPermitsHandler.Delete(ctx, in, out)
}

func (h *frontPermitsHandler) UpdateOrCreate(ctx context.Context, in *Request, out *Response) error {
	return h.FrontPermitsHandler.UpdateOrCreate(ctx, in, out)
}
