// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/frontPermit/frontPermit.proto

package frontPermit

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FrontPermit struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	App                  string   `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	Service              string   `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Method               string   `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Permission           []string `protobuf:"bytes,7,rep,name=permission,proto3" json:"permission,omitempty"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FrontPermit) Reset()         { *m = FrontPermit{} }
func (m *FrontPermit) String() string { return proto.CompactTextString(m) }
func (*FrontPermit) ProtoMessage()    {}
func (*FrontPermit) Descriptor() ([]byte, []int) {
	return fileDescriptor_e01d8dcd8aa06d26, []int{0}
}

func (m *FrontPermit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrontPermit.Unmarshal(m, b)
}
func (m *FrontPermit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrontPermit.Marshal(b, m, deterministic)
}
func (m *FrontPermit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrontPermit.Merge(m, src)
}
func (m *FrontPermit) XXX_Size() int {
	return xxx_messageInfo_FrontPermit.Size(m)
}
func (m *FrontPermit) XXX_DiscardUnknown() {
	xxx_messageInfo_FrontPermit.DiscardUnknown(m)
}

var xxx_messageInfo_FrontPermit proto.InternalMessageInfo

func (m *FrontPermit) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FrontPermit) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *FrontPermit) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *FrontPermit) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *FrontPermit) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FrontPermit) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *FrontPermit) GetPermission() []string {
	if m != nil {
		return m.Permission
	}
	return nil
}

func (m *FrontPermit) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *FrontPermit) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type ListQuery struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 int64    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Sort                 string   `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Service              string   `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Method               string   `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListQuery) Reset()         { *m = ListQuery{} }
func (m *ListQuery) String() string { return proto.CompactTextString(m) }
func (*ListQuery) ProtoMessage()    {}
func (*ListQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_e01d8dcd8aa06d26, []int{1}
}

func (m *ListQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListQuery.Unmarshal(m, b)
}
func (m *ListQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListQuery.Marshal(b, m, deterministic)
}
func (m *ListQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListQuery.Merge(m, src)
}
func (m *ListQuery) XXX_Size() int {
	return xxx_messageInfo_ListQuery.Size(m)
}
func (m *ListQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ListQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ListQuery proto.InternalMessageInfo

func (m *ListQuery) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListQuery) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListQuery) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *ListQuery) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ListQuery) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *ListQuery) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_e01d8dcd8aa06d26, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	FrontPermit          *FrontPermit   `protobuf:"bytes,1,opt,name=frontPermit,proto3" json:"frontPermit,omitempty"`
	FrontPermits         []*FrontPermit `protobuf:"bytes,2,rep,name=frontPermits,proto3" json:"frontPermits,omitempty"`
	Total                int64          `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Valid                bool           `protobuf:"varint,4,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e01d8dcd8aa06d26, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetFrontPermit() *FrontPermit {
	if m != nil {
		return m.FrontPermit
	}
	return nil
}

func (m *Response) GetFrontPermits() []*FrontPermit {
	if m != nil {
		return m.FrontPermits
	}
	return nil
}

func (m *Response) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Response) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*FrontPermit)(nil), "frontPermit.FrontPermit")
	proto.RegisterType((*ListQuery)(nil), "frontPermit.ListQuery")
	proto.RegisterType((*Request)(nil), "frontPermit.Request")
	proto.RegisterType((*Response)(nil), "frontPermit.Response")
}

func init() {
	proto.RegisterFile("proto/frontPermit/frontPermit.proto", fileDescriptor_e01d8dcd8aa06d26)
}

var fileDescriptor_e01d8dcd8aa06d26 = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xc1, 0x8a, 0x13, 0x41,
	0x10, 0x75, 0xd2, 0xc9, 0x24, 0x53, 0x59, 0x16, 0x29, 0xd6, 0xa5, 0x11, 0x94, 0x61, 0xbc, 0xe4,
	0xb4, 0xc2, 0x2a, 0x28, 0xea, 0x25, 0xac, 0xac, 0x17, 0x41, 0x6d, 0xf0, 0x2c, 0x63, 0xa6, 0xd4,
	0x86, 0x49, 0xba, 0xed, 0xae, 0x2c, 0xf8, 0x15, 0xfe, 0x8a, 0xe0, 0xb7, 0x79, 0x97, 0xee, 0x99,
	0x75, 0x3b, 0xe2, 0x78, 0x98, 0x5b, 0xbd, 0x57, 0xf5, 0x32, 0xf5, 0xea, 0x35, 0x81, 0x07, 0xd6,
	0x19, 0x36, 0x0f, 0x3f, 0x39, 0xb3, 0xe3, 0xb7, 0xe4, 0xb6, 0x9a, 0xd3, 0xfa, 0x2c, 0x76, 0x71,
	0x99, 0x50, 0xd5, 0xaf, 0x0c, 0x96, 0x97, 0x37, 0x18, 0x8f, 0x61, 0xa2, 0x1b, 0x99, 0x95, 0xd9,
	0x4a, 0xa8, 0x89, 0x6e, 0xf0, 0x36, 0x88, 0xda, 0x5a, 0x39, 0x29, 0xb3, 0x55, 0xa1, 0x42, 0x89,
	0x12, 0xe6, 0x9e, 0xdc, 0x95, 0xde, 0x90, 0x14, 0x91, 0xbd, 0x86, 0x78, 0x0a, 0xf9, 0x96, 0xf8,
	0x8b, 0x69, 0xe4, 0x34, 0x36, 0x7a, 0x84, 0x08, 0xd3, 0x5d, 0xbd, 0x25, 0x39, 0x8b, 0x6c, 0xac,
	0xb1, 0x84, 0x65, 0x43, 0x7e, 0xe3, 0xb4, 0x65, 0x6d, 0x76, 0x32, 0x8f, 0xad, 0x94, 0xc2, 0xfb,
	0x00, 0x36, 0xec, 0xe4, 0x7d, 0x18, 0x98, 0x97, 0x62, 0x55, 0xa8, 0x84, 0xc1, 0x7b, 0x00, 0x1b,
	0x47, 0x35, 0x53, 0xf3, 0xa1, 0x66, 0xb9, 0x88, 0x3f, 0x50, 0xf4, 0xcc, 0x9a, 0x43, 0x7b, 0x6f,
	0x9b, 0xeb, 0x76, 0xd1, 0xb5, 0x7b, 0x66, 0xcd, 0xd5, 0xf7, 0x0c, 0x8a, 0xd7, 0xda, 0xf3, 0xbb,
	0x3d, 0xb9, 0x6f, 0x78, 0x02, 0xb3, 0x56, 0x6f, 0x35, 0xf7, 0xc6, 0x3b, 0x10, 0xf6, 0xb6, 0xf5,
	0x67, 0x8a, 0xe6, 0x85, 0x8a, 0x75, 0xe0, 0xbc, 0x71, 0xdc, 0x5b, 0x8f, 0x75, 0x7a, 0x91, 0xe9,
	0xd0, 0x45, 0x66, 0xff, 0xbc, 0x48, 0x7e, 0x73, 0x91, 0xaa, 0x80, 0xb9, 0xa2, 0xaf, 0x7b, 0xf2,
	0x5c, 0xfd, 0xc8, 0x60, 0xa1, 0xc8, 0x5b, 0xb3, 0xf3, 0x84, 0xcf, 0x20, 0x0d, 0x2c, 0x6e, 0xb8,
	0x3c, 0x97, 0x67, 0x69, 0xae, 0x49, 0x80, 0x2a, 0x1d, 0xc6, 0x17, 0x70, 0x94, 0x40, 0x2f, 0x27,
	0xa5, 0xf8, 0xaf, 0xf8, 0x60, 0x3a, 0x5c, 0x85, 0x0d, 0xd7, 0x6d, 0x34, 0x2b, 0x54, 0x07, 0x02,
	0x7b, 0x55, 0xb7, 0xba, 0x0b, 0x79, 0xa1, 0x3a, 0x70, 0xfe, 0x53, 0xc0, 0xd1, 0x65, 0x2a, 0x7e,
	0x0c, 0x62, 0xdd, 0xb6, 0x78, 0x72, 0xf0, 0xad, 0xde, 0xe0, 0xdd, 0x3b, 0x7f, 0xb1, 0x9d, 0xd5,
	0xea, 0x16, 0x3e, 0x81, 0x69, 0x48, 0x05, 0x4f, 0x0f, 0x06, 0xfe, 0x04, 0x35, 0x2c, 0x7c, 0x0a,
	0xe2, 0x15, 0x31, 0x0e, 0x5a, 0x1b, 0x56, 0x3e, 0x87, 0xfc, 0x22, 0xbe, 0x9a, 0x91, 0xe2, 0xf7,
	0xf1, 0x4d, 0x8d, 0x14, 0xbf, 0xa4, 0x96, 0xc6, 0x89, 0x2f, 0xe0, 0xb8, 0xfb, 0xf2, 0x1b, 0x37,
	0x7a, 0xfd, 0x8f, 0x79, 0xfc, 0x47, 0x78, 0xf4, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x42, 0x8b,
	0x12, 0x38, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for FrontPermits service

type FrontPermitsClient interface {
	// 权限验证授权
	// 全部权限
	All(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 获取权限列表
	List(ctx context.Context, in *ListQuery, opts ...client.CallOption) (*Response, error)
	// 根据 唯一 获取权限
	Get(ctx context.Context, in *FrontPermit, opts ...client.CallOption) (*Response, error)
	// 创建权限
	Create(ctx context.Context, in *FrontPermit, opts ...client.CallOption) (*Response, error)
	// 更新权限
	Update(ctx context.Context, in *FrontPermit, opts ...client.CallOption) (*Response, error)
	// 删除权限
	Delete(ctx context.Context, in *FrontPermit, opts ...client.CallOption) (*Response, error)
	// 同步前端权限 允许外部权限  需要最高 root 权限  *********高危 调用慎重*********
	UpdateOrCreate(ctx context.Context, in *FrontPermit, opts ...client.CallOption) (*Response, error)
}

type frontPermitsClient struct {
	c           client.Client
	serviceName string
}

func NewFrontPermitsClient(serviceName string, c client.Client) FrontPermitsClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "frontPermit"
	}
	return &frontPermitsClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *frontPermitsClient) All(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "FrontPermits.All", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontPermitsClient) List(ctx context.Context, in *ListQuery, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "FrontPermits.List", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontPermitsClient) Get(ctx context.Context, in *FrontPermit, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "FrontPermits.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontPermitsClient) Create(ctx context.Context, in *FrontPermit, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "FrontPermits.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontPermitsClient) Update(ctx context.Context, in *FrontPermit, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "FrontPermits.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontPermitsClient) Delete(ctx context.Context, in *FrontPermit, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "FrontPermits.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontPermitsClient) UpdateOrCreate(ctx context.Context, in *FrontPermit, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "FrontPermits.UpdateOrCreate", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FrontPermits service

type FrontPermitsHandler interface {
	// 权限验证授权
	// 全部权限
	All(context.Context, *Request, *Response) error
	// 获取权限列表
	List(context.Context, *ListQuery, *Response) error
	// 根据 唯一 获取权限
	Get(context.Context, *FrontPermit, *Response) error
	// 创建权限
	Create(context.Context, *FrontPermit, *Response) error
	// 更新权限
	Update(context.Context, *FrontPermit, *Response) error
	// 删除权限
	Delete(context.Context, *FrontPermit, *Response) error
	// 同步前端权限 允许外部权限  需要最高 root 权限  *********高危 调用慎重*********
	UpdateOrCreate(context.Context, *FrontPermit, *Response) error
}

func RegisterFrontPermitsHandler(s server.Server, hdlr FrontPermitsHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&FrontPermits{hdlr}, opts...))
}

type FrontPermits struct {
	FrontPermitsHandler
}

func (h *FrontPermits) All(ctx context.Context, in *Request, out *Response) error {
	return h.FrontPermitsHandler.All(ctx, in, out)
}

func (h *FrontPermits) List(ctx context.Context, in *ListQuery, out *Response) error {
	return h.FrontPermitsHandler.List(ctx, in, out)
}

func (h *FrontPermits) Get(ctx context.Context, in *FrontPermit, out *Response) error {
	return h.FrontPermitsHandler.Get(ctx, in, out)
}

func (h *FrontPermits) Create(ctx context.Context, in *FrontPermit, out *Response) error {
	return h.FrontPermitsHandler.Create(ctx, in, out)
}

func (h *FrontPermits) Update(ctx context.Context, in *FrontPermit, out *Response) error {
	return h.FrontPermitsHandler.Update(ctx, in, out)
}

func (h *FrontPermits) Delete(ctx context.Context, in *FrontPermit, out *Response) error {
	return h.FrontPermitsHandler.Delete(ctx, in, out)
}

func (h *FrontPermits) UpdateOrCreate(ctx context.Context, in *FrontPermit, out *Response) error {
	return h.FrontPermitsHandler.UpdateOrCreate(ctx, in, out)
}
