// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string   `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Origin               string   `protobuf:"bytes,8,opt,name=origin,proto3" json:"origin,omitempty"`
	CreatedAt            string   `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *User) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type ListQuery struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 int64    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Sort                 string   `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Mobile               string   `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListQuery) Reset()         { *m = ListQuery{} }
func (m *ListQuery) String() string { return proto.CompactTextString(m) }
func (*ListQuery) ProtoMessage()    {}
func (*ListQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *ListQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListQuery.Unmarshal(m, b)
}
func (m *ListQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListQuery.Marshal(b, m, deterministic)
}
func (m *ListQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListQuery.Merge(m, src)
}
func (m *ListQuery) XXX_Size() int {
	return xxx_messageInfo_ListQuery.Size(m)
}
func (m *ListQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ListQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ListQuery proto.InternalMessageInfo

func (m *ListQuery) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListQuery) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListQuery) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *ListQuery) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ListQuery) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *ListQuery) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Roles                []string `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	User                 *User    `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Users                []*User  `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	Total                int64    `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Response) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Response) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*ListQuery)(nil), "user.ListQuery")
	proto.RegisterType((*Request)(nil), "user.Request")
	proto.RegisterType((*Response)(nil), "user.Response")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x5f, 0xab, 0xd3, 0x30,
	0x14, 0xb7, 0x6d, 0xda, 0xb5, 0x47, 0x9c, 0x10, 0x54, 0xc2, 0x40, 0x29, 0x15, 0xff, 0xbd, 0x4c,
	0x98, 0x9f, 0x60, 0xa8, 0x88, 0xe0, 0x8b, 0x81, 0x3d, 0x4b, 0x66, 0xe3, 0x08, 0xb4, 0x4d, 0x4d,
	0xd2, 0xa9, 0x5f, 0xc2, 0x17, 0x3f, 0x80, 0xdf, 0xf4, 0x72, 0xc9, 0x49, 0x3b, 0x76, 0x2f, 0xbb,
	0xf4, 0x65, 0x3b, 0xbf, 0x3f, 0x3b, 0x39, 0xf9, 0x9d, 0x0c, 0x1e, 0xf7, 0x46, 0x3b, 0xfd, 0x76,
	0xb0, 0xd2, 0xe0, 0xc7, 0x1a, 0x31, 0x25, 0xbe, 0xae, 0xae, 0x22, 0x20, 0x3b, 0x2b, 0x0d, 0x5d,
	0x42, 0xac, 0x6a, 0x16, 0x95, 0xd1, 0xeb, 0x82, 0xc7, 0xaa, 0xa6, 0x2b, 0xc8, 0xbd, 0xa1, 0x13,
	0xad, 0x64, 0x31, 0xb2, 0x27, 0x4c, 0x9f, 0x40, 0xd6, 0xea, 0xbd, 0x6a, 0x24, 0x4b, 0x50, 0x19,
	0x11, 0x7d, 0x04, 0xa9, 0x6c, 0x85, 0x6a, 0x18, 0x41, 0x3a, 0x00, 0xdf, 0xa9, 0x17, 0xd6, 0xfe,
	0xd2, 0xa6, 0x66, 0x69, 0xe8, 0x34, 0x61, 0x4a, 0x81, 0xe0, 0x09, 0x19, 0xf2, 0x64, 0xea, 0x2e,
	0x8e, 0xc2, 0x09, 0xc3, 0x16, 0xa1, 0x7b, 0x40, 0x9e, 0xd7, 0x46, 0x1d, 0x54, 0xc7, 0xf2, 0xc0,
	0x07, 0x44, 0x9f, 0x02, 0x7c, 0x37, 0x52, 0x38, 0x59, 0x7f, 0x13, 0x8e, 0x15, 0xa8, 0x15, 0x23,
	0xb3, 0x75, 0x5e, 0x1e, 0xfa, 0x7a, 0x92, 0x21, 0xc8, 0x23, 0xb3, 0x75, 0xd5, 0xbf, 0x08, 0x8a,
	0x2f, 0xca, 0xba, 0xaf, 0x83, 0x34, 0x7f, 0xfc, 0x0d, 0x1a, 0xd5, 0x2a, 0x87, 0x41, 0x24, 0x3c,
	0x00, 0x3f, 0x65, 0x2f, 0x0e, 0x21, 0x87, 0x84, 0x63, 0xed, 0x39, 0xab, 0x8d, 0x1b, 0x13, 0xc0,
	0xfa, 0x46, 0x66, 0xe4, 0xce, 0xcc, 0xd2, 0xcb, 0x99, 0x65, 0x67, 0x99, 0x55, 0x05, 0x2c, 0xb8,
	0xfc, 0x39, 0x48, 0xeb, 0xaa, 0xbf, 0x11, 0xe4, 0x5c, 0xda, 0x5e, 0x77, 0x16, 0xdd, 0x47, 0xd1,
	0x8c, 0x8b, 0xca, 0x79, 0x00, 0x9e, 0x35, 0xba, 0x91, 0x96, 0xc5, 0x65, 0xe2, 0x7b, 0x20, 0xa0,
	0xcf, 0x00, 0x57, 0x8c, 0x13, 0xde, 0xdf, 0xc0, 0x1a, 0x77, 0xef, 0x77, 0xcd, 0x91, 0xa7, 0x25,
	0xa4, 0xfe, 0xdb, 0x32, 0x52, 0x26, 0xb7, 0x0c, 0x41, 0xf0, 0x7d, 0x9d, 0x76, 0xa2, 0xc1, 0x91,
	0x13, 0x1e, 0xc0, 0xe6, 0x7f, 0x0c, 0xe9, 0x0e, 0xf5, 0x17, 0x90, 0x7e, 0xfc, 0xad, 0xac, 0xa3,
	0x67, 0xbf, 0x5d, 0x2d, 0x43, 0x3d, 0x8d, 0x5c, 0xdd, 0xa3, 0xaf, 0x80, 0x7c, 0xee, 0x7e, 0x68,
	0xfa, 0x60, 0x52, 0xf0, 0x62, 0x17, 0x8c, 0x6f, 0x80, 0xf8, 0x55, 0xd0, 0x87, 0x41, 0x39, 0xad,
	0xe5, 0x82, 0xf5, 0x39, 0x24, 0x9f, 0xe4, 0xdc, 0xc1, 0x2f, 0x21, 0x7b, 0x8f, 0xef, 0x60, 0xde,
	0xb7, 0xc3, 0x07, 0x31, 0xef, 0xfb, 0x20, 0x1b, 0x39, 0xe7, 0xdb, 0x67, 0xf8, 0x0f, 0x7b, 0x77,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0x30, 0x40, 0x8d, 0xe4, 0x7a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Users service

type UsersClient interface {
	// 用过 用户名、邮箱、手机 查询用户是否存在
	Exist(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	// 根据 唯一 获取用户
	Info(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 获取用户列表
	List(ctx context.Context, in *ListQuery, opts ...client.CallOption) (*Response, error)
	// 根据 唯一 获取用户
	Get(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	// 创建用户
	Create(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	// 更新用户
	Update(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	// 删除用户
	Delete(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
}

type usersClient struct {
	c           client.Client
	serviceName string
}

func NewUsersClient(serviceName string, c client.Client) UsersClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "user"
	}
	return &usersClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *usersClient) Exist(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Users.Exist", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Info(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Users.Info", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) List(ctx context.Context, in *ListQuery, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Users.List", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Get(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Users.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Create(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Users.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Update(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Users.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Delete(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Users.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Users service

type UsersHandler interface {
	// 用过 用户名、邮箱、手机 查询用户是否存在
	Exist(context.Context, *User, *Response) error
	// 根据 唯一 获取用户
	Info(context.Context, *Request, *Response) error
	// 获取用户列表
	List(context.Context, *ListQuery, *Response) error
	// 根据 唯一 获取用户
	Get(context.Context, *User, *Response) error
	// 创建用户
	Create(context.Context, *User, *Response) error
	// 更新用户
	Update(context.Context, *User, *Response) error
	// 删除用户
	Delete(context.Context, *User, *Response) error
}

func RegisterUsersHandler(s server.Server, hdlr UsersHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Users{hdlr}, opts...))
}

type Users struct {
	UsersHandler
}

func (h *Users) Exist(ctx context.Context, in *User, out *Response) error {
	return h.UsersHandler.Exist(ctx, in, out)
}

func (h *Users) Info(ctx context.Context, in *Request, out *Response) error {
	return h.UsersHandler.Info(ctx, in, out)
}

func (h *Users) List(ctx context.Context, in *ListQuery, out *Response) error {
	return h.UsersHandler.List(ctx, in, out)
}

func (h *Users) Get(ctx context.Context, in *User, out *Response) error {
	return h.UsersHandler.Get(ctx, in, out)
}

func (h *Users) Create(ctx context.Context, in *User, out *Response) error {
	return h.UsersHandler.Create(ctx, in, out)
}

func (h *Users) Update(ctx context.Context, in *User, out *Response) error {
	return h.UsersHandler.Update(ctx, in, out)
}

func (h *Users) Delete(ctx context.Context, in *User, out *Response) error {
	return h.UsersHandler.Delete(ctx, in, out)
}
