// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Origin               string   `protobuf:"bytes,6,opt,name=origin,proto3" json:"origin,omitempty"`
	CreatedAt            string   `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *User) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type Info struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string   `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Introduction         string   `protobuf:"bytes,3,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Roles                []string `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Info) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Info) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *Info) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Info                 *Info    `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	Valid                bool     `protobuf:"varint,4,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Response) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *Response) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*Info)(nil), "user.Info")
	proto.RegisterType((*Request)(nil), "user.Request")
	proto.RegisterType((*Response)(nil), "user.Response")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcb, 0x4e, 0xeb, 0x30,
	0x14, 0xbc, 0x79, 0x36, 0x3d, 0xf7, 0xaa, 0x0b, 0xeb, 0x82, 0xac, 0x4a, 0xa0, 0x28, 0x3c, 0xc4,
	0xaa, 0x48, 0xe5, 0x0b, 0x2a, 0x84, 0x10, 0xdb, 0x48, 0x5d, 0x23, 0xb7, 0x71, 0x91, 0xa5, 0xd4,
	0x0e, 0xb6, 0x53, 0x58, 0xf3, 0x27, 0xfc, 0x12, 0x5f, 0x84, 0x7c, 0xec, 0x54, 0xc0, 0x82, 0x6e,
	0x12, 0xcf, 0xcc, 0xc9, 0xe4, 0xcc, 0xc8, 0x70, 0xd4, 0x69, 0x65, 0xd5, 0x75, 0x6f, 0xb8, 0xc6,
	0xc7, 0x0c, 0x31, 0x49, 0xdd, 0xb9, 0xfa, 0x88, 0x20, 0x5d, 0x1a, 0xae, 0xc9, 0x04, 0x62, 0xd1,
	0xd0, 0xa8, 0x8c, 0xae, 0xc6, 0x75, 0x2c, 0x1a, 0x32, 0x85, 0xc2, 0x0d, 0x48, 0xb6, 0xe5, 0x34,
	0x46, 0x76, 0x8f, 0xc9, 0x31, 0xe4, 0x5b, 0xb5, 0x12, 0x2d, 0xa7, 0x09, 0x2a, 0x01, 0x91, 0xff,
	0x90, 0xf1, 0x2d, 0x13, 0x2d, 0x4d, 0x91, 0xf6, 0xc0, 0x39, 0x75, 0xcc, 0x98, 0x17, 0xa5, 0x1b,
	0x9a, 0x79, 0xa7, 0x01, 0x3b, 0x27, 0xa5, 0xc5, 0x93, 0x90, 0x34, 0xf7, 0x4e, 0x1e, 0x91, 0x13,
	0x80, 0xb5, 0xe6, 0xcc, 0xf2, 0xe6, 0x91, 0x59, 0x3a, 0x42, 0x6d, 0x1c, 0x98, 0x85, 0x75, 0x72,
	0xdf, 0x35, 0x83, 0x5c, 0x78, 0x39, 0x30, 0x0b, 0x5b, 0xb5, 0x90, 0x3e, 0xc8, 0x8d, 0x22, 0x04,
	0x52, 0xdc, 0xdf, 0xa7, 0x4a, 0x87, 0xdd, 0xd9, 0x8e, 0x59, 0xa6, 0x43, 0xaa, 0x80, 0x48, 0x05,
	0xff, 0x84, 0xb4, 0x5a, 0x35, 0xfd, 0xda, 0x0a, 0x25, 0x43, 0xb2, 0x6f, 0x9c, 0xcb, 0xa7, 0x55,
	0xcb, 0x0d, 0x4d, 0xcb, 0xc4, 0xe5, 0x43, 0x50, 0x8d, 0x61, 0x54, 0xf3, 0xe7, 0x9e, 0x1b, 0x5b,
	0xbd, 0x45, 0x50, 0xd4, 0xdc, 0x74, 0x4a, 0x1a, 0x4e, 0x4e, 0x01, 0x2b, 0xc6, 0xbf, 0xff, 0x9d,
	0xc3, 0x0c, 0xbb, 0x77, 0x5d, 0xd7, 0xc8, 0x93, 0x12, 0x32, 0xf7, 0x36, 0x34, 0x2e, 0x93, 0x1f,
	0x03, 0x5e, 0x70, 0x0e, 0x42, 0x6e, 0x14, 0xee, 0xb2, 0x1f, 0x70, 0xc9, 0x6a, 0xe4, 0xdd, 0x3e,
	0x3b, 0xd6, 0x8a, 0x06, 0xfb, 0x2e, 0x6a, 0x0f, 0xe6, 0xef, 0x11, 0x64, 0x4b, 0xfc, 0xfe, 0x12,
	0xf2, 0x5b, 0xec, 0x8c, 0x7c, 0x31, 0x9f, 0x4e, 0xfc, 0x79, 0xd8, 0xb3, 0xfa, 0x43, 0x2e, 0x20,
	0xbb, 0x7b, 0x15, 0xc6, 0x1e, 0x18, 0x3b, 0x0f, 0xb5, 0xfe, 0x3e, 0x75, 0x06, 0xc9, 0x3d, 0x3f,
	0x60, 0xb5, 0xca, 0xf1, 0x0e, 0xde, 0x7c, 0x06, 0x00, 0x00, 0xff, 0xff, 0x7b, 0xa1, 0xcd, 0x8f,
	0x9c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Users service

type UsersClient interface {
	// 创建用户
	Create(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	// 用过 用户名、邮箱、手机 查询用户是否存在
	Exist(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	// 获取用户基本信息
	Info(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	// 根据 唯一 获取用户
	Get(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
}

type usersClient struct {
	c           client.Client
	serviceName string
}

func NewUsersClient(serviceName string, c client.Client) UsersClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "user"
	}
	return &usersClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *usersClient) Create(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Users.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Exist(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Users.Exist", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Info(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Users.Info", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Get(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Users.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Users service

type UsersHandler interface {
	// 创建用户
	Create(context.Context, *User, *Response) error
	// 用过 用户名、邮箱、手机 查询用户是否存在
	Exist(context.Context, *User, *Response) error
	// 获取用户基本信息
	Info(context.Context, *User, *Response) error
	// 根据 唯一 获取用户
	Get(context.Context, *User, *Response) error
}

func RegisterUsersHandler(s server.Server, hdlr UsersHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Users{hdlr}, opts...))
}

type Users struct {
	UsersHandler
}

func (h *Users) Create(ctx context.Context, in *User, out *Response) error {
	return h.UsersHandler.Create(ctx, in, out)
}

func (h *Users) Exist(ctx context.Context, in *User, out *Response) error {
	return h.UsersHandler.Exist(ctx, in, out)
}

func (h *Users) Info(ctx context.Context, in *User, out *Response) error {
	return h.UsersHandler.Info(ctx, in, out)
}

func (h *Users) Get(ctx context.Context, in *User, out *Response) error {
	return h.UsersHandler.Get(ctx, in, out)
}
