// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/casbin/casbin.proto

package casbin

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Permission struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Method               string   `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Permission) Reset()         { *m = Permission{} }
func (m *Permission) String() string { return proto.CompactTextString(m) }
func (*Permission) ProtoMessage()    {}
func (*Permission) Descriptor() ([]byte, []int) {
	return fileDescriptor_f835afd114115d9e, []int{0}
}

func (m *Permission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Permission.Unmarshal(m, b)
}
func (m *Permission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Permission.Marshal(b, m, deterministic)
}
func (m *Permission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permission.Merge(m, src)
}
func (m *Permission) XXX_Size() int {
	return xxx_messageInfo_Permission.Size(m)
}
func (m *Permission) XXX_DiscardUnknown() {
	xxx_messageInfo_Permission.DiscardUnknown(m)
}

var xxx_messageInfo_Permission proto.InternalMessageInfo

func (m *Permission) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Permission) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type Request struct {
	Group                string        `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Role                 string        `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Roles                []string      `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Permission           *Permission   `protobuf:"bytes,4,opt,name=permission,proto3" json:"permission,omitempty"`
	Permissions          []*Permission `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_f835afd114115d9e, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *Request) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Request) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Request) GetPermission() *Permission {
	if m != nil {
		return m.Permission
	}
	return nil
}

func (m *Request) GetPermissions() []*Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type Response struct {
	Valid                bool          `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserID               string        `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Role                 string        `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Roles                []string      `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	Permission           *Permission   `protobuf:"bytes,5,opt,name=permission,proto3" json:"permission,omitempty"`
	Permissions          []*Permission `protobuf:"bytes,6,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f835afd114115d9e, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Response) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Response) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Response) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Response) GetPermission() *Permission {
	if m != nil {
		return m.Permission
	}
	return nil
}

func (m *Response) GetPermissions() []*Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func init() {
	proto.RegisterType((*Permission)(nil), "casbin.Permission")
	proto.RegisterType((*Request)(nil), "casbin.Request")
	proto.RegisterType((*Response)(nil), "casbin.Response")
}

func init() { proto.RegisterFile("proto/casbin/casbin.proto", fileDescriptor_f835afd114115d9e) }

var fileDescriptor_f835afd114115d9e = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0xad, 0xdd, 0xba, 0x79, 0x86, 0xff, 0x82, 0x48, 0xf4, 0xaa, 0xf4, 0x6a, 0x57, 0x1b,
	0xd4, 0x09, 0x5e, 0x09, 0xc3, 0xc1, 0xf0, 0x4e, 0x02, 0x3e, 0x40, 0xb7, 0x1c, 0xb4, 0xd0, 0x35,
	0x35, 0x49, 0xf7, 0x60, 0xfa, 0x1a, 0x3e, 0x94, 0x34, 0x49, 0xd7, 0x5e, 0x38, 0xe8, 0x76, 0x95,
	0x7e, 0xe9, 0xf7, 0x83, 0xef, 0x3b, 0x87, 0xc0, 0x5d, 0x21, 0x85, 0x16, 0xd3, 0x75, 0xa2, 0x56,
	0x69, 0xee, 0x8e, 0x89, 0xb9, 0x23, 0x81, 0x55, 0xd1, 0x33, 0xc0, 0x1b, 0xca, 0x4d, 0xaa, 0x54,
	0x2a, 0x72, 0x42, 0x61, 0xa0, 0x50, 0x6e, 0xd3, 0x35, 0x52, 0x2f, 0xf4, 0xc6, 0x67, 0xac, 0x96,
	0xe4, 0x16, 0x82, 0x0d, 0xea, 0x4f, 0xc1, 0xe9, 0xa9, 0xf9, 0xe1, 0x54, 0xf4, 0xe3, 0xc1, 0x80,
	0xe1, 0x57, 0x89, 0x4a, 0x93, 0x1b, 0xe8, 0x7f, 0x48, 0x51, 0x16, 0x8e, 0xb5, 0x82, 0x10, 0xe8,
	0x49, 0x91, 0xa1, 0xe3, 0xcc, 0x77, 0xe5, 0xac, 0x4e, 0x45, 0xfd, 0xd0, 0xaf, 0x9c, 0x46, 0x90,
	0x18, 0xa0, 0xd8, 0x65, 0xa1, 0xbd, 0xd0, 0x1b, 0x8f, 0x62, 0x32, 0x71, 0xb1, 0x9b, 0x94, 0xac,
	0xe5, 0x22, 0x33, 0x18, 0x35, 0x4a, 0xd1, 0x7e, 0xe8, 0xef, 0x81, 0xda, 0xb6, 0xe8, 0xd7, 0x83,
	0x21, 0x43, 0x55, 0x88, 0x5c, 0x99, 0x30, 0xdb, 0x24, 0x4b, 0xb9, 0x89, 0x3d, 0x64, 0x56, 0x54,
	0x85, 0x4b, 0x85, 0xf2, 0x75, 0x51, 0x17, 0xb6, 0x6a, 0x57, 0xc7, 0xff, 0xaf, 0x4e, 0x6f, 0x7f,
	0x9d, 0xfe, 0x31, 0x75, 0x82, 0x4e, 0x75, 0xe2, 0x6f, 0x1f, 0x82, 0x17, 0x63, 0x21, 0x33, 0x38,
	0x9f, 0x73, 0xde, 0x5a, 0xe9, 0x65, 0x0d, 0xbb, 0x2d, 0xdd, 0x5f, 0x35, 0x17, 0x76, 0x00, 0xd1,
	0x09, 0x79, 0x82, 0xeb, 0x05, 0x66, 0xa8, 0xb1, 0x01, 0x55, 0x67, 0xf2, 0xbd, 0xe0, 0xc9, 0x11,
	0xe4, 0x23, 0x5c, 0x2c, 0x51, 0x1f, 0x8c, 0x4d, 0x60, 0x30, 0xe7, 0x9c, 0x55, 0x63, 0xef, 0xe4,
	0x8f, 0x61, 0x64, 0xab, 0x31, 0xb3, 0x94, 0xae, 0x8c, 0x2d, 0x75, 0x00, 0x33, 0x85, 0xe1, 0x12,
	0x75, 0x77, 0x60, 0x15, 0x98, 0x87, 0xf8, 0xf0, 0x17, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x8e, 0x85,
	0x52, 0xa5, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Casbin service

type CasbinClient interface {
	// 角色权限管理
	AddPermission(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	DeletePermissions(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	UpdatePermissions(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	GetPermissions(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 用户角色管理
	AddRole(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	DeleteRoles(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	UpdateRoles(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	GetRoles(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type casbinClient struct {
	c           client.Client
	serviceName string
}

func NewCasbinClient(serviceName string, c client.Client) CasbinClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "casbin"
	}
	return &casbinClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *casbinClient) AddPermission(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Casbin.AddPermission", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *casbinClient) DeletePermissions(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Casbin.DeletePermissions", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *casbinClient) UpdatePermissions(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Casbin.UpdatePermissions", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *casbinClient) GetPermissions(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Casbin.GetPermissions", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *casbinClient) AddRole(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Casbin.AddRole", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *casbinClient) DeleteRoles(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Casbin.DeleteRoles", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *casbinClient) UpdateRoles(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Casbin.UpdateRoles", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *casbinClient) GetRoles(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Casbin.GetRoles", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Casbin service

type CasbinHandler interface {
	// 角色权限管理
	AddPermission(context.Context, *Request, *Response) error
	DeletePermissions(context.Context, *Request, *Response) error
	UpdatePermissions(context.Context, *Request, *Response) error
	GetPermissions(context.Context, *Request, *Response) error
	// 用户角色管理
	AddRole(context.Context, *Request, *Response) error
	DeleteRoles(context.Context, *Request, *Response) error
	UpdateRoles(context.Context, *Request, *Response) error
	GetRoles(context.Context, *Request, *Response) error
}

func RegisterCasbinHandler(s server.Server, hdlr CasbinHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Casbin{hdlr}, opts...))
}

type Casbin struct {
	CasbinHandler
}

func (h *Casbin) AddPermission(ctx context.Context, in *Request, out *Response) error {
	return h.CasbinHandler.AddPermission(ctx, in, out)
}

func (h *Casbin) DeletePermissions(ctx context.Context, in *Request, out *Response) error {
	return h.CasbinHandler.DeletePermissions(ctx, in, out)
}

func (h *Casbin) UpdatePermissions(ctx context.Context, in *Request, out *Response) error {
	return h.CasbinHandler.UpdatePermissions(ctx, in, out)
}

func (h *Casbin) GetPermissions(ctx context.Context, in *Request, out *Response) error {
	return h.CasbinHandler.GetPermissions(ctx, in, out)
}

func (h *Casbin) AddRole(ctx context.Context, in *Request, out *Response) error {
	return h.CasbinHandler.AddRole(ctx, in, out)
}

func (h *Casbin) DeleteRoles(ctx context.Context, in *Request, out *Response) error {
	return h.CasbinHandler.DeleteRoles(ctx, in, out)
}

func (h *Casbin) UpdateRoles(ctx context.Context, in *Request, out *Response) error {
	return h.CasbinHandler.UpdateRoles(ctx, in, out)
}

func (h *Casbin) GetRoles(ctx context.Context, in *Request, out *Response) error {
	return h.CasbinHandler.GetRoles(ctx, in, out)
}
